# Generated by Django 5.0.6 on 2024-06-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=45, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=45, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=45, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo Electrónico')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extrangería')], max_length=2, verbose_name='Tipo de Documento')),
                ('documento', models.PositiveIntegerField(unique=True, verbose_name='Documento')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
