# Generated by Django 5.0.6 on 2024-06-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0003_conductor_password_alter_conductor_placa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='password',
        ),
        migrations.AddField(
            model_name='conductor',
            name='password1',
            field=models.CharField(default='', max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='password2',
            field=models.CharField(default='', max_length=128, verbose_name='Confirme la Contraseña'),
        ),
    ]
