# Generated by Django 5.0.6 on 2024-06-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0005_conductor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='user',
        ),
    ]
