# Generated by Django 5.0.6 on 2024-06-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0007_conductor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo Apellido'),
        ),
    ]
